STACK_ENTITIES: true
ENTITY_MERGE_RADIUS: 5.0
ENTITY_MERGE_AMOUNT: 6
MERGE_SPAWNER_ENTITIES_ONLY: false
MENTALLY_CHALLENGED_MOBS: true
MAX_ENTITES_PER_CHUNK: 55
END_MOBS_ALWAYS_ACTIVE: true
STACKABLE_MOB_TYPES: []
CHICKEN_EGG_TIME_MS: 240000