noPerm: '&4You do not have permission to do /backup.'
help:
  '1': '&b&lUsage:'
  '2': '&a/backup create &7-&e Creates backup'
  '3': '&a/backup cancel &7-&e Cancels any backup in progress'
  '4': '&a/backup info &7-&e Check if a backup is in progress and get other info'
  '5': '&a/backup reload &7-&e Reloads the config'
  '6': '&a/backup restore <backup> &7-&e Restores a backup'
restore:
  info: '&cRestoring a backup can fail, so a backup will be made before attempting
    to restore. ONLY the files in the backup you are restoring will be restored. Any
    new files, or exempt files will be removed.'
  choose: '&6Backups you can restore: &7'
  noBackups: '&cThere are no backups in your backup folder.'
  currentcolor: '&7'
  noExist: '&cThat backup file does not exist.'
  backupInProgress: '&cA backup is currently in progress.'
  restoreInProgress: '&cRestore already in progress'
  backupName: RestoreBackup_%time%
  failed: '&cFailed to restore backup.'
  begin: '&aRestoring!'
  backupComplete: '&aRestore backup complete, stopping server in 30 seconds to complete
    the restore. Do not start the server until restoring is complete! When the file
    ''restore_log.txt'' appears in your server folder, the restore process has completed.'
  restoreInProgressAll: '&cA restore process is in progress. EasyBackup commands disabled.
    DO NOT RESTART YOUR SERVER WHILE RESTORING.'
info:
  backupSchedule: '&6Backup schedule: &7'
  delay: '&6Backup Delay (Hours): &7'
  maxbk: '&6Max backups: &7'
  backingup: '&6Backing up: &7'
  percent: '&6Backup percent: &7'
  compression: '&6Compression: &7'
  current: '&6Current files in backup folder:'
  currentcolor: '&7'
noCancel: '&cThere is no backup to cancel.'
inProgress: '&cA backup is in already progress.'
reloaded: '&aConfig reloaded.'
failedReload: '&cFAILED TO RELOAD CONFIG - Error message sent to console.'
startFrom: '&6[EasyBackup] &fStarting server backup from: '
savingTo: '&6[EasyBackup] &fSaving to: '
backupSaved: '&6[EasyBackup] &fBackup saved!'
failedToSaveBk: '&6[EasyBackup] &cFAILED TO SAVE BACKUP!'
debug:
  zipping: '&6[EasyBackup] &fZipping file: &7'
  zippingFolder: '&6[EasyBackup] &fZipping folder: &7'
failedToZipFile: '&6[EasyBackup] &cFAILED TO ZIP FILE: &7'
failedToZipFolder: '&6[EasyBackup] &cFAILED TO ZIP FOLDER: &7'
backupStarted: '&aBackup started.'
savedPercent: '&6[EasyBackup] &9Backup: &7%percent%% %mb% / %totalmb% mb saved.'
canceledBk: '&aCanceled backup.'
slowDown: '&6[EasyBackup] &cBackup slowing down since server is lagging.'
speedUp: '&6[EasyBackup] &fBackup has returned back to max speed.'
noInGameCommands: '&cIn game commands have been disabed by the EasyBackup config.'
ftp:
  start: '&6Starting FTP upload.'
  folder: '&6Created FTP folder.'
  finished: '&6Finished FTP upload!'
  failed: '&cFTP UPLOAD FAILED!'
  loginFailed: '&cFTP LOGIN FAILED.'
  login: '&6Logged into FTP server.'
  connectFailed: '&cFTP CONNECTION FAILED.'
  percent: '&fFTP Backup percent: &7'
  timeout: '&cFTP connection timed out.'
  trySSH: '&6Attempting to connect to ftp via SSH.'
  connectedSSH: '&6Connection established!'
  loadingDir: '&6Loading FTP save directory.'
  beginSSH: '&6Starting SSH upload!'
  deleteAfter: '&fDeleting local backup file.'
  failedDelete: '&cFailed to delete local backup file!'
  successDelete: '&aLocal backup file deleted! Backup complete!'
  tryProtocol: '&6Using protocol: '
  fileLoadFail: '&cFailed to load backup file. Is it being used by another program?'
