partners:
  Zigy:
    aliases:
    - Ziggy
  Dylan_:
    aliases:
    - Dylan
    - Loser
  Resucting:
    aliases:
    - Resu
  NotRamix:
    aliases:
    - Ramix
  FlushaAimLock:
    aliases:
    - Flusha
    - FlushaAimSex
    - ballz
    - balls
    - GovernmentExperiment
  iMakeMcVids:
    aliases:
    - iMake
  Vik:
    aliases:
    - VikStar123
    - Walmart
  Zylowh:
    aliases: []
  Rheiley:
    aliases: []
  Headed:
    aliases:
    - Headass
    - virgin
    - edater
  OmarSmosh:
    aliases: []
  Samfay:
    aliases:
    - SamHCF
    - virgin2
    - edater2
    - ratio
  Informing:
    aliases:
    - Then
  stevvn:
    aliases:
    - steven
  Lectors:
    aliases:
    - shitter
  Frozeado:
    aliases: []
  Nicoarg17:
    aliases: []
  Houp:
    aliases: []
  Eamotyn:
    aliases: []
  Elivann:
    aliases: []
  TobiiM9:
    aliases:
    - tobim9
    - tobi
  QnA:
    aliases:
    - FatLard
    - Billy
  Rowin:
    aliases:
    - Emma
  Lokonazo1:
    aliases:
    - Lokonazo
